environment: production
environmentCode:
name: automatey
namespace: automatey
workstream: automatey
image: automatey

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: automatey-config-map

containerSecret:
  name: automatey-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
