services:
  automatey:
    build:
      context: .
      target: production
    image: automatey
    container_name: automatey
    environment:
      APPINSIGHTS_CLOUDROLE: automatey-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
